import { useState } from 'react'
import { landingCopy } from './content/landing-copy'

const C = { graphite: '#1C1F26', graphite2: '#22262f', blue: '#1F4F82', cyan: '#1FA7A3', deck: '#F5F7FA', steel: '#A3A9B5', dim: '#6b7280', green: '#3BB273' }
type Page = 'home' | 'figures' | 'rules' | 'lore' | 'profile'
const figures = Array.from({ length: 27 }, (_, i) => i + 1)

function Grid() {
  return <div className="relative border border-[#1FA7A3]/25 bg-[#22262f] p-4">
    <div className="absolute left-4 top-2 font-mono text-[9px] tracking-[.12em] text-[#1FA7A3]/70">CONTAINER 15×11 / TRAINING VIEW</div>
    <div className="mt-5 grid grid-cols-15 grid-rows-11 border border-[#1FA7A3]/20">
      {Array.from({ length: 165 }, (_, i) => <span key={i} className="h-5 border-b border-r border-[#1FA7A3]/10" />)}
    </div>
    <div className="pointer-events-none absolute bottom-[36px] left-4 right-4 grid grid-cols-15">
      {Array.from({ length: 15 }, (_, i) => <span key={i} className="h-5 border border-[#3BB273] bg-[#3BB273]/20" />)}
    </div>
    <div className="absolute bottom-2 left-4 right-4 flex justify-between font-mono text-[8px] text-[#6b7280]">{[0,3,6,9,12,14].map(x => <span key={x}>{x}</span>)}</div>
  </div>
}

function SectionLabel({ children }: { children: string }) { return <p className="mb-3 font-mono text-[11px] tracking-[.16em] text-[#1FA7A3]">{children}</p> }
function Button({ children, onClick, primary = false }: { children: string; onClick?: () => void; primary?: boolean }) { return <button onClick={onClick} className={`border px-5 py-3 text-sm transition hover:-translate-y-0.5 ${primary ? 'border-[#1FA7A3] bg-[#1FA7A3] font-semibold text-[#1C1F26]' : 'border-[#1F4F82] text-[#F5F7FA] hover:bg-[#1F4F82]/15'}`}>{children}</button> }

function Home({ setPage }: { setPage: (p: Page) => void }) {
  const [faq, setFaq] = useState<number | null>(null)
  return <div className="bg-[#1C1F26] text-[#F5F7FA]">
    <section className="min-h-screen bg-[linear-gradient(rgba(31,167,163,.05)_1px,transparent_1px),linear-gradient(90deg,rgba(31,167,163,.05)_1px,transparent_1px)] bg-[length:24px_24px] px-6 pb-20 pt-28">
      <div className="mx-auto grid max-w-7xl items-center gap-16 md:grid-cols-2">
        <div><SectionLabel>{landingCopy.hero.eyebrow}</SectionLabel><h1 className="mb-6 text-5xl font-bold leading-[1.05] tracking-tight md:text-7xl">{landingCopy.hero.title[0]}<br /><span className="text-[#1FA7A3]">{landingCopy.hero.title[1]}</span><br />{landingCopy.hero.title[2]}</h1><p className="mb-8 max-w-xl text-base leading-relaxed text-[#A3A9B5]">{landingCopy.hero.description}</p><div className="flex flex-wrap gap-3"><Button primary onClick={() => setPage('profile')}>{landingCopy.hero.primaryCta}</Button><Button onClick={() => document.getElementById('rules')?.scrollIntoView()}>{landingCopy.hero.secondaryCta}</Button><Button onClick={() => setPage('figures')}>{landingCopy.hero.tertiaryCta}</Button></div><div className="mt-10 border-l-2 border-[#1F4F82] pl-4"><p className="font-mono text-[10px] tracking-[.12em] text-[#6b7280]">{landingCopy.hero.proofLabel}</p><code className="font-mono text-[#1FA7A3]">{landingCopy.hero.proofNotation}</code><span className="ml-3 text-xs text-[#6b7280]">{landingCopy.hero.proofDescription}</span></div></div>
        <div><Grid /><div className="mt-4 flex justify-end gap-4 text-xs"><span className="text-[#3BB273]">■ Row A closed</span><span className="text-[#A3A9B5]">■ Placed</span><span className="text-[#1FA7A3]">● Entry A0</span></div><p className="mt-4 border border-[#1FA7A3]/20 p-3 text-xs text-[#6b7280]">{landingCopy.hero.visualNote}</p><div className="mt-5 flex items-center gap-4 border border-[#1F4F82]/40 p-3 font-mono text-xs text-[#1FA7A3]"><span className="text-[#6b7280]">{landingCopy.hero.incomingLabel}</span><span>▦</span>{landingCopy.hero.incomingDescription}</div></div>
      </div>
    </section>

    <section className="border-y border-[#1FA7A3]/10 bg-[#22262f] px-6 py-20 text-center"><div className="mx-auto max-w-3xl"><SectionLabel>{landingCopy.difference.eyebrow}</SectionLabel><h2 className="mb-6 text-3xl font-bold md:text-5xl">{landingCopy.difference.title}</h2><p className="leading-relaxed text-[#A3A9B5]">{landingCopy.difference.description}</p></div></section>

    <section id="rules" className="px-6 py-24"><div className="mx-auto max-w-7xl"><SectionLabel>{landingCopy.rules.eyebrow}</SectionLabel><h2 className="mb-12 text-3xl font-semibold">{landingCopy.rules.title}</h2><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{landingCopy.rules.items.map(item => <article key={item.number} className="border border-[#1FA7A3]/20 bg-[#22262f] p-6"><span className="font-mono text-xs text-[#1FA7A3]">{item.number}</span><h3 className="my-8 text-xl font-semibold">{item.title}</h3><p className="text-sm leading-relaxed text-[#A3A9B5]">{item.description}</p></article>)}</div></div></section>

    <section className="border-t border-[#1FA7A3]/10 bg-[#22262f] px-6 py-24"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-6"><div><SectionLabel>{landingCopy.figures.eyebrow}</SectionLabel><h2 className="text-3xl font-semibold">{landingCopy.figures.title}</h2><p className="mt-3 text-[#A3A9B5]">{landingCopy.figures.description}</p></div><Button onClick={() => setPage('figures')}>{landingCopy.figures.cta}</Button></div><div className="mt-12 grid grid-cols-3 gap-3 sm:grid-cols-6 md:grid-cols-9">{figures.slice(0, 18).map(id => <button key={id} onClick={() => setPage('figures')} className="aspect-square border border-[#1FA7A3]/15 bg-[#1C1F26] p-3 font-mono text-xs text-[#1FA7A3] hover:border-[#1FA7A3]/60">F{String(id).padStart(2, '0')}</button>)}</div></div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><SectionLabel>{landingCopy.qualification.eyebrow}</SectionLabel><h2 className="text-3xl font-semibold">{landingCopy.qualification.title}</h2><p className="mt-3 max-w-2xl text-[#A3A9B5]">{landingCopy.qualification.description}</p><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{landingCopy.qualification.tiers.map(([abbr, name, desc]) => <article key={name} className="border border-[#1FA7A3]/20 bg-[#22262f] p-4"><div className="mb-8 inline-flex h-8 w-8 items-center justify-center bg-[#1FA7A3] font-mono text-xs text-[#1C1F26]">{abbr}</div><h3 className="text-sm font-semibold text-[#1FA7A3]">{name}</h3><p className="mt-2 text-xs text-[#6b7280]">{desc}</p></article>)}</div></div></section>

    <section className="border-y border-[#1FA7A3]/10 bg-[#22262f] px-6 py-24"><div className="mx-auto max-w-4xl border-l-2 border-[#1FA7A3] pl-8"><h2 className="mb-6 text-3xl font-semibold">“{landingCopy.integrity.quote}”</h2><p className="mb-5 max-w-2xl leading-relaxed text-[#A3A9B5]">{landingCopy.integrity.body}</p><p className="text-sm text-[#6b7280]">{landingCopy.integrity.audience}</p></div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><SectionLabel>{landingCopy.modes.eyebrow}</SectionLabel><h2 className="mb-10 text-3xl font-semibold">{landingCopy.modes.title}</h2><div className="grid gap-6 md:grid-cols-3">{landingCopy.modes.items.map(mode => <article key={mode.title} className="flex flex-col border border-[#1FA7A3]/20 bg-[#22262f] p-6"><div className="flex justify-between font-mono text-[10px] tracking-[.12em] text-[#1FA7A3]"><span>{mode.tag}</span><span className="text-[#6b7280]">{mode.badge}</span></div><h3 className="mt-8 text-xl font-semibold">{mode.title}</h3><p className="my-5 flex-1 text-sm leading-relaxed text-[#A3A9B5]">{mode.description}</p><div className="flex items-center justify-between"><span className="border border-[#1F4F82] px-2 py-1 font-mono text-xs text-[#1FA7A3]">{mode.size}</span><Button onClick={() => setPage(mode.title === 'Sandbox' ? 'figures' : 'profile')}>{mode.cta}</Button></div></article>)}</div></div></section>

    <section className="border-y border-[#1F4F82]/50 bg-[#1F4F82]/20 px-6 py-20"><div className="mx-auto grid max-w-5xl gap-12 md:grid-cols-2"><div><SectionLabel>{landingCopy.pairsec.eyebrow}</SectionLabel><h2 className="mb-5 text-3xl font-semibold">{landingCopy.pairsec.title}</h2><p className="mb-6 text-[#A3A9B5]">{landingCopy.pairsec.description}</p><a className="inline-block border border-[#1FA7A3]/50 px-4 py-2 text-[#1FA7A3]" href="https://pairsec.com" target="_blank" rel="noreferrer">{landingCopy.pairsec.cta} →</a></div><div className="border border-[#1F4F82]/50 bg-[#1C1F26]/50 p-6 font-mono text-xs text-[#A3A9B5]"><p className="mb-4 tracking-[.12em] text-[#6b7280]">QUALIFICATION BRIDGE</p><p className="border-b border-[#1FA7A3]/10 py-3 text-[#1FA7A3]">MidLod+ → performer status</p><p className="border-b border-[#1FA7A3]/10 py-3 text-[#1FA7A3]">LeadLod+ → verified specialist</p><p className="py-3 text-[#1FA7A3]">ProfiLod → Judge / Consultant</p></div></div></section>

    <section className="px-6 py-24"><div className="mx-auto max-w-3xl"><SectionLabel>{landingCopy.faq.eyebrow}</SectionLabel><h2 className="mb-10 text-3xl font-semibold">{landingCopy.faq.title}</h2>{landingCopy.faq.items.map(([q, a], i) => <div key={q} className="border-t border-[#1FA7A3]/15"><button onClick={() => setFaq(faq === i ? null : i)} className="flex w-full justify-between py-5 text-left font-medium">{q}<span className="text-[#1FA7A3]">{faq === i ? '×' : '+'}</span></button>{faq === i && <p className="pb-5 text-sm leading-relaxed text-[#A3A9B5]">{a}</p>}</div>)}</div></section>

    <footer className="border-t border-[#1FA7A3]/10 bg-[#22262f] px-6 py-14"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-10"><div><div className="mb-4 font-mono tracking-[.08em] text-[#F5F7FA]">▦ PUZZLESTOW</div><p className="max-w-xs text-sm text-[#6b7280]">{landingCopy.footer.description}</p></div><div className="font-mono text-xs text-[#6b7280]">PLAY · FIGURES · RULES · LORE · PRINT & PLAY</div></div></footer>
  </div>
}

function SimplePage({ title, setPage }: { title: string; setPage: (p: Page) => void }) { return <div className="min-h-screen bg-[#1C1F26] px-6 pb-24 pt-32 text-[#F5F7FA]"><div className="mx-auto max-w-5xl"><p className="mb-4 font-mono text-xs tracking-[.16em] text-[#1FA7A3]">PUZZLESTOW</p><h1 className="text-5xl font-bold">{title}</h1><p className="mt-5 max-w-xl text-[#A3A9B5]">This screen remains available in the prototype. Return to the landing page for the full product story.</p><button className="mt-8 border border-[#1FA7A3] px-5 py-3 text-[#1FA7A3]" onClick={() => setPage('home')}>Back home</button></div></div> }

export default function App() { const [page, setPage] = useState<Page>('home'); return <><header className="fixed left-0 right-0 top-0 z-50 flex h-14 items-center justify-between border-b border-[#1FA7A3]/15 bg-[#1C1F26]/95 px-6 backdrop-blur"><button onClick={() => setPage('home')} className="font-mono text-sm tracking-[.08em] text-[#F5F7FA]">▦ PUZZLESTOW</button><nav className="hidden gap-7 text-sm text-[#A3A9B5] md:flex"><button onClick={() => setPage('figures')}>Figures</button><button onClick={() => setPage('rules')}>Rules</button><button onClick={() => setPage('lore')}>Lore</button><button onClick={() => setPage('profile')}>Profile</button></nav><button onClick={() => setPage('profile')} className="bg-[#1F4F82] px-4 py-2 text-sm font-semibold text-[#F5F7FA]">Play</button></header>{page === 'home' ? <Home setPage={setPage} /> : <SimplePage title={page === 'figures' ? 'Figure catalog' : page === 'rules' ? 'Rules' : page === 'lore' ? 'Legend of the Lodars' : 'Start your first match'} setPage={setPage} />}</> }
